from faker import Faker
from sqlalchemy.orm import Session
from src.database.db import SessionLocal
from src.database.models import Contact
import random


def generate_fake_contacts(n):
    fake = Faker('uk_UA')
    db = SessionLocal()

    for _ in range(n):
        contact = Contact(
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            email=fake.email(),
            phone_number=fake.phone_number(),
            birthday=fake.date_of_birth(),
            additional_data="Generated by Faker"
        )
        db.add(contact)

    db.commit()
    db.close()


if __name__ == "__main__":
    generate_fake_contacts(100)  # Генерувати 100 фейкових контактів
